version: "3.8"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    command: /bin/sh -c "chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html && nginx -g 'daemon off;'"
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html
    command: /bin/sh -c "chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html && php-fpm"

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
